### PR TITLE
oauth: allow passing additional credential data to providers

### PR DESCRIPTION
**Pull request by AlexCuse**

### CODE REVIEW

**Comment by AlexCuse** [comment]
This will be needed to pass some additional data (key ID + team ID) to the apple provider.  The signing key could be included in the additional map as well I suppose but since that can be used by all providers I think it makes sense to include as a top-level detail.

**Comment by AlexCuse** [comment]
@cainlevy any concerns about this?  I have the Apple implementation near ready to test built on top of this.

Feeling like it will be time to do configuration files next 😅

**Review by cainlevy — APPROVED** [review]
😆 😭 🙈 ok yeah why not

**Comment by AlexCuse** [comment]
Yea might merge with the Apple stuff to keep blame where it belongs for posterity 😅

**Comment by AlexCuse** [comment]
Included in #243

**Pull request closed without merging**
