### PR TITLE
Added public routes for /jwks and /configuration

### LINKED ISSUE #197: /jwks endpoint is not public
The documentation mentions that the `/jwks` endpoint has [Public visibility](https://keratin.github.io/authn-server/#/api?id=json-web-keys), but I am not able to access it on the public API. Only the private API seems to expose it.

I would like to be able to access the `/jwks` endpoint through the public API so that I can verify JWT tokens in my API Gateway.

The `/configuration` endpoint is also specified as being public, but is only available on the private API.

### PR DESCRIPTION
**Pull request by Probotect0r**
Closes #197 

I haven't been able to get the dev environment working, so haven't been able to test this. Although, the changes are simple copy and paste.

Here's what I am running into (not a Go developer so please advise on anything obvious):
```
go install
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:117843:10: warning: function may return address of local variable [-Wreturn-local-addr]
117843 |   return pNew;
       |          ^~~~
sqlite3-binding.c:117802:10: note: declared here
117802 |   Select standin;
       |          ^~~~~~~
ego server/views
make: ego: No such file or directory
make: *** [Makefile:14: init] Error 127
```
Seems like I also need `ego` installed, but I have run `go get github.com/go-ego/ego` without success. 

Also, the main readme mentions `make docker`, but that target doesn't exist in the Makefile.

### CODE REVIEW

**Comment by cainlevy** [comment]
@Probotect0r thanks for the feedback. looks like the "contributing" docs are indeed out of date. for this, i believe `make test` and `make server` are all that you will need.

> I have run `go get github.com/go-ego/ego` without success.

Took me a moment to uncover the problem but this appears to be a different "ego" library. AuthN relies on `go get github.com/benbjohnson/ego` instead. That used to be part of the `go.mod` list until a recent PR.

Sorry for the rough start! Let me know if this is helpful.

**Comment by Probotect0r** [comment]
That's helpful, thanks. I was able to get `make server` working. I have confirmed that the `jwks` and `/configuration` routes are now available on both the public and private API. However, `make test` is failing due to this failed test:

```
--- FAIL: TestAccountStore (0.00s)
    account_store_test.go:40:
                Error Trace:    account_store_test.go:40
                Error:          Received unexpected error:
                                dial tcp 127.0.0.1:8703: connect: connection refused
                                NewDB
                                github.com/keratin/authn-server/app/data/postgres_test.newTestDB
                                        /home/sagar/Code/authn-server/app/data/postgres/account_store_test.go:29
                                github.com/keratin/authn-server/app/data/postgres_test.TestAccountStore
                                        /home/sagar/Code/authn-server/app/data/postgres/account_store_test.go:39
                                testing.tRunner
                                        /home/sagar/.asdf/installs/golang/1.17.2/go/src/testing/testing.go:1259
                                runtime.goexit
                                        /home/sagar/.asdf/installs/golang/1.17.2/go/src/runtime/asm_amd64.s:1581
                Test:           TestAccountStore
FAIL
FAIL    github.com/keratin/authn-server/app/data/postgres       0.006s
ok      github.com/keratin/authn-server/app/data/private        (cached)
```

I don't believe this is related to my code changes. Any ideas?

**Comment by Probotect0r** [comment]
Ah, figured it out. My Postgres container was not starting up via docker-compose due to not specifying `DB_PASSWORD` and `DB_USERNAME` in the .env. All tests are passing now.

**Comment by cainlevy** [comment]
Looks good! Congrats, you're a go developer now. 😄

**Comment by cainlevy** [comment]
Released in https://github.com/keratin/authn-server/releases/tag/v1.15.0

**Pull request merged**
